# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61sic.proto\x12\x05\x62\x61sic\"\x07\n\x05\x45mpty\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\x10PlayerProvinceId\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x13\n\x0bprovince_id\x18\x02 \x01(\x05\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x08\"\x16\n\x05\x43ount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x97\x01\n\x05\x42\x61sic\x12(\n\x04\x45\x63ho\x12\x0e.basic.Message\x1a\x0e.basic.Message\"\x00\x12\x38\n\x0fPutControlToken\x12\x17.basic.PlayerProvinceId\x1a\n.basic.Key\"\x00\x12*\n\nRoundCount\x12\x0c.basic.Empty\x1a\x0c.basic.Count\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=22
  _EMPTY._serialized_end=29
  _MESSAGE._serialized_start=31
  _MESSAGE._serialized_end=57
  _PLAYERPROVINCEID._serialized_start=59
  _PLAYERPROVINCEID._serialized_end=117
  _KEY._serialized_start=119
  _KEY._serialized_end=137
  _COUNT._serialized_start=139
  _COUNT._serialized_end=161
  _BASIC._serialized_start=164
  _BASIC._serialized_end=315
# @@protoc_insertion_point(module_scope)
